# Generated by Django 2.2 on 2020-08-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200727_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-modified']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
