# Generated by Django 2.2 on 2020-08-06 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_hitcountbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitcountbase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='hitcountbase',
            name='modified',
        ),
        migrations.AddField(
            model_name='hitcountbase',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2020, 8, 6)),
            preserve_default=False,
        ),
    ]
