# Generated by Django 2.2 on 2020-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200725_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Comment'),
        ),
    ]
