# Generated by Django 2.2 on 2020-08-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200802_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
            preserve_default=False,
        ),
    ]
