# Generated by Django 2.2 on 2020-08-06 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_auto_20200806_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hitcountbase',
            unique_together={('pub_date', 'user', 'page_url'), ('pub_date', 'ip', 'page_url')},
        ),
    ]
