# Generated by Django 2.2 on 2020-08-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200806_2129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hitcountbase',
            unique_together=set(),
        ),
    ]
