# Generated by Django 2.2 on 2020-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200807_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=500, null=True, upload_to='products/images', verbose_name='Image', width_field=500),
        ),
    ]
