# Generated by Django 2.2 on 2020-08-11 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200807_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hitcountbase',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
