# Generated by Django 2.2 on 2020-08-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200811_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
